// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace CRUD_DBF_core.Models
{
    internal class ModelBuilder
    {
        internal void Entity<T>(Action<object> value)
        {
            throw new NotImplementedException();
        }
    }
}